import React from "react";

const districts = ["अल्मोड़ा", "बागेश्वर", "चमोली", "चम्पावत", "देहरादून", "हरिद्वार", "नैनीताल", "पौड़ी गढ़वाल", "पिथौरागढ़", "रुद्रप्रयाग", "टिहरी गढ़वाल", "उधम सिंह नगर", "उत्तरकाशी"];
const natureOptions = ["किसी व्यक्ति के जीवन की रक्षा", "स्वयं के जीवन की रक्षा हेतु साहसिक कार्य", "आपदा/प्राकृतिक आपदा में साहसिक कार्य", "दुर्घटना में बचाव कार्य", "डूबते हुए व्यक्ति को बचाना", "आग/अग्निकांड में बचाव कार्य", "अपराध/आपराधिक घटना के दौरान साहसिक कार्य", "अन्य असाधारण साहसिक कार्य"];

const StepC = ({ data, update, error }) => {
  const input = (label, name, options = {}) => <div className={`nf-field ${options.wide ? "nf-wide" : ""}`}><label htmlFor={`nf-${name}`}>{label}{options.required && <span> *</span>}</label>{options.options ? <select id={`nf-${name}`} name={name} value={data[name] || ""} onChange={update}><option value="">चयन करें</option>{options.options.map((option) => <option key={option}>{option}</option>)}</select> : options.textarea ? <textarea id={`nf-${name}`} name={name} value={data[name] || ""} onChange={update} rows={options.rows || 4} /> : <input id={`nf-${name}`} name={name} type={options.type || "text"} value={data[name] || ""} onChange={update} />}{error[name] && <small className="nf-error">{error[name]}</small>}</div>;
  const witnessFields = ["नाम", "मोबाइल नंबर", "पता", "बच्चे से संबंध"];
  return <section className="nf-card"><div className="nf-card-heading"><span>Step 2</span><h2>वीरता की घटना का विवरण (Details of Bravery Act)</h2></div>{input("1. वीरता की घटना का शीर्षक", "actTitle", { required: true })}<p className="nf-hint">(संक्षेप में घटना का शीर्षक लिखें)</p><div className="nf-grid">{input("2. घटना की दिनांक", "actDate", { required: true, type: "date" })}{input("3. घटना का समय", "actTime", { type: "time" })}{input("4. घटना का स्थान", "actPlace", { required: true })}{input("5. घटना का जनपद", "actDistrict", { required: true, options: districts })}{input("6. घटना की प्रकृति", "actNature", { required: true, options: natureOptions })}</div>{input("7. घटना का संक्षिप्त विवरण", "shortDescription", { required: true, textarea: true, wide: true })}<p className="nf-hint">(अधिकतम 500 शब्द)</p>{input("8. बच्चे द्वारा किये गये साहसिक/वीरतापूर्ण कार्य का विस्तृत विवरण", "detailedDescription", { required: true, textarea: true, wide: true, rows: 7 })}<p className="nf-hint">(न्यूनतम 500 शब्द)</p><div className="nf-grid">{input("9. घटना के दौरान बच्चे द्वारा बचाये गये व्यक्ति/व्यक्तियों की संख्या", "rescuedCount", { type: "number" })}{input("10. बचाये गये व्यक्ति/व्यक्तियों का विवरण (यदि लागू हो)", "rescuedDetails", { textarea: true })}</div><fieldset className="nf-subsection"><legend>घटना के प्रत्यक्षदर्शियों का विवरण</legend><div className="nf-table-wrap"><table className="nf-table"><thead><tr>{["क्र.सं.", ...witnessFields].map((field) => <th key={field}>{field}</th>)}</tr></thead><tbody>{[1, 2, 3].map((row) => <tr key={row}><td>{row}</td>{witnessFields.map((field) => <td key={field}><input aria-label={`${row}. ${field}`} name={`witness${row}${field}`} value={data[`witness${row}${field}`] || ""} onChange={update} /></td>)}</tr>)}</tbody></table></div></fieldset><div className="nf-grid">{input("12. घटना के संबंध में पुलिस रिपोर्ट/FIR दर्ज है?", "firRegistered", { required: true, options: ["हाँ", "नहीं", "लागू नहीं"] })}{input("13. क्या घटना के संबंध में कोई समाचार/मीडिया रिपोर्ट प्रकाशित हुई है?", "mediaPublished", { options: ["हाँ", "नहीं"] })}</div>{data.firRegistered === "हाँ" && <div className="nf-grid nf-conditional">{input("थाना", "policeStation", { required: true })}{input("FIR संख्या", "firNumber", { required: true })}{input("FIR दिनांक", "firDate", { required: true, type: "date" })}</div>}{data.mediaPublished === "हाँ" && input("यदि हाँ, विवरण:", "mediaDetails", { textarea: true, wide: true })}</section>;
};
export default StepC;